In [ ]:
# Part C — Load and Data Audit

""This notebook loads the selected datasets and performs basic data audits,
including dataset size, unique patient counts, and missingness analysis.""

In [1]:
import pandas as pd

In [3]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
radiology = pd.read_excel(
    "../data/raw/tcga-ov/TCIA_TCGA-OV_09-16-2015-nbia-digest.xlsx"
)

In [7]:
radiology.head()

,Patient ID,Patient Name,Patient Birth Date,Patient Sex,Ethnic Group,Phantom,Species Code,Species Description,Study Instance UID,Study Date,...,Manufacturer Model Name,Software Versions,Image Count,Max Submission Timestamp,License Name,License URI,Collection URI,File Size,Date Released,Third Party Analysis
0,TCGA-24-0966,TCGA-24-0966,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.330693106714...,1992-05-01 00:00:00.0,...,Sensation 64,syngo CT 2007S,2,2013-08-28 23:24:07.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,1054346,2013-08-28 23:24:07.0,NaN
1,TCGA-24-0966,TCGA-24-0966,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.330693106714...,1992-05-01 00:00:00.0,...,Sensation 64,syngo CT 2007S,114,2013-08-28 23:24:45.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,60104818,2013-08-28 23:24:45.0,NaN
2,TCGA-24-0966,TCGA-24-0966,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.330693106714...,1992-05-01 00:00:00.0,...,Sensation 64,syngo CT 2007S,51,2013-08-28 23:24:58.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,26889056,2013-08-28 23:24:58.0,NaN
3,TCGA-24-0966,TCGA-24-0966,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.662271560962...,1992-05-04 00:00:00.0,...,Sensation 64,syngo CT 2007S,3,2013-08-28 23:29:02.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,1581274,2013-08-28 23:29:02.0,NaN
4,TCGA-24-0966,TCGA-24-0966,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.662271560962...,1992-05-04 00:00:00.0,...,Sensation 64,syngo CT 2007S,1,2013-08-28 23:29:02.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,527222,2013-08-28 23:29:02.0,NaN

In [8]:
radiology.shape

(844, 36)

In [9]:
radiology.columns

Index(['Patient ID', 'Patient Name', 'Patient Birth Date', 'Patient Sex',
       'Ethnic Group', 'Phantom', 'Species Code', 'Species Description',
       'Study Instance UID', 'Study Date', 'Study Description',
       'Admitting Diagnosis Description', 'Study ID', 'Patient Age',
       'Longitudinal Temporal Event Type',
       'Longitudinal Temporal Offset From Event', 'Series Instance UID',
       'Project', 'Modality', 'Protocol Name', 'Series Date',
       'Series Description', 'Body Part Examined', 'Series Number',
       'Annotations Flag', 'Manufacturer', 'Manufacturer Model Name',
       'Software Versions', 'Image Count', 'Max Submission Timestamp',
       'License Name', 'License URI', 'Collection URI', 'File Size',
       'Date Released', 'Third Party Analysis'],
      dtype='object')

In [11]:
radiology['Patient ID'].nunique()

143

In [16]:
# Missingness (% missing per column) — Radiology
radiology.isna().mean().mul(100).sort_values()

Patient ID                                   0.000000
File Size                                    0.000000
Collection URI                               0.000000
License URI                                  0.000000
License Name                                 0.000000
Max Submission Timestamp                     0.000000
Image Count                                  0.000000
Body Part Examined                           0.000000
Modality                                     0.000000
Date Released                                0.000000
Series Instance UID                          0.000000
Project                                      0.000000
Patient Name                                 0.000000
Species Code                                 0.000000
Study Date                                   0.000000
Study Instance UID                           0.000000
Phantom                                      0.000000
Species Description                          0.000000
Patient Sex                                  0.000000
Series Number                                0.118483
Study Description                            0.236967
Manufacturer Model Name                      0.355450
Manufacturer                                 0.355450
Patient Age                                  0.829384
Series Date                                  0.829384
Series Description                           2.369668
Software Versions                            2.488152
Protocol Name                               11.966825
Admitting Diagnosis Description             97.156398
Ethnic Group                                98.222749
Patient Birth Date                         100.000000
Study ID                                   100.000000
Longitudinal Temporal Offset From Event    100.000000
Longitudinal Temporal Event Type           100.000000
Annotations Flag                           100.000000
Third Party Analysis                       100.000000
dtype: float64

In [17]:
proteogenomics = pd.read_excel(
    "../data/raw/tcga_ov_proteogenomics/2020-02-26_Images_from_HGSOC_proteomics-nbia-digest.xlsx"
)

In [20]:
proteogenomics.head()

,Patient ID,Patient Name,Patient Birth Date,Patient Sex,Ethnic Group,Phantom,Species Code,Species Description,Study Instance UID,Study Date,...,Manufacturer Model Name,Software Versions,Image Count,Max Submission Timestamp,License Name,License URI,Collection URI,File Size,Date Released,Third Party Analysis
0,TCGA-24-1103,TCGA-24-1103,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.287113235960...,1985-11-06 00:00:00.0,...,Volume Zoom,VA20Q,2,2013-08-28 23:42:09.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,1054960,2013-08-28 23:42:09.0,NaN
1,TCGA-24-1103,TCGA-24-1103,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.287113235960...,1985-11-06 00:00:00.0,...,Volume Zoom,VA20Q,45,2013-08-28 23:42:26.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,23735520,2013-08-28 23:42:26.0,NaN
2,TCGA-24-1103,TCGA-24-1103,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.287113235960...,1985-11-06 00:00:00.0,...,Volume Zoom,VA20Q,45,2013-08-28 23:42:38.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,23735430,2013-08-28 23:42:38.0,NaN
3,TCGA-24-1103,TCGA-24-1103,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.287113235960...,1985-11-06 00:00:00.0,...,Volume Zoom,VA20Q,92,2013-08-28 23:43:07.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,48526320,2013-08-28 23:43:07.0,NaN
4,TCGA-24-1103,TCGA-24-1103,NaN,F,NaN,NO,337915000,Homo sapiens,1.3.6.1.4.1.14519.5.2.1.7777.4007.287113235960...,1985-11-06 00:00:00.0,...,Volume Zoom,VA20Q,20,2013-08-28 23:43:12.0,Creative Commons Attribution 3.0 Unported License,http://creativecommons.org/licenses/by/3.0/,https://doi.org/10.7937/K9/TCIA.2016.NDO1MDFQ,10549160,2013-08-28 23:43:12.0,NaN

In [21]:
proteogenomics.shape

(87, 36)

In [22]:
proteogenomics.columns

Index(['Patient ID', 'Patient Name', 'Patient Birth Date', 'Patient Sex',
       'Ethnic Group', 'Phantom', 'Species Code', 'Species Description',
       'Study Instance UID', 'Study Date', 'Study Description',
       'Admitting Diagnosis Description', 'Study ID', 'Patient Age',
       'Longitudinal Temporal Event Type',
       'Longitudinal Temporal Offset From Event', 'Series Instance UID',
       'Project', 'Modality', 'Protocol Name', 'Series Date',
       'Series Description', 'Body Part Examined', 'Series Number',
       'Annotations Flag', 'Manufacturer', 'Manufacturer Model Name',
       'Software Versions', 'Image Count', 'Max Submission Timestamp',
       'License Name', 'License URI', 'Collection URI', 'File Size',
       'Date Released', 'Third Party Analysis'],
      dtype='object')

In [23]:
proteogenomics['Patient ID'].nunique()

20

In [24]:
proteogenomics.isna().mean().mul(100).sort_values()

Patient ID                                   0.000000
File Size                                    0.000000
Collection URI                               0.000000
License URI                                  0.000000
License Name                                 0.000000
Max Submission Timestamp                     0.000000
Image Count                                  0.000000
Manufacturer Model Name                      0.000000
Manufacturer                                 0.000000
Series Number                                0.000000
Body Part Examined                           0.000000
Series Date                                  0.000000
Modality                                     0.000000
Date Released                                0.000000
Series Instance UID                          0.000000
Project                                      0.000000
Study Instance UID                           0.000000
Patient Age                                  0.000000
Patient Name                                 0.000000
Study Description                            0.000000
Study Date                                   0.000000
Patient Sex                                  0.000000
Species Description                          0.000000
Species Code                                 0.000000
Phantom                                      0.000000
Series Description                           2.298851
Software Versions                            4.597701
Protocol Name                               12.643678
Admitting Diagnosis Description             91.954023
Patient Birth Date                         100.000000
Longitudinal Temporal Event Type           100.000000
Longitudinal Temporal Offset From Event    100.000000
Annotations Flag                           100.000000
Study ID                                   100.000000
Ethnic Group                               100.000000
Third Party Analysis                       100.000000
dtype: float64